Write a program to implement k-Nearest Neighbour algorithm to classify the iris data set. Print 
both correct and wrong predictions. Java/Python ML library classes can be used for this problem. 

In [3]:
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
from sklearn.model_selection import train_test_split
import numpy as np

dataset=load_iris()
X_train,X_test,y_train,y_test=train_test_split(dataset["data"], dataset["target"],random_state=0,test_size=0.25)
 
kn=KNeighborsClassifier(n_neighbors=5,p=3,metric='euclidean')
kn.fit(X_train,y_train)
y_pred=kn.predict(X_test)

print('Confusion matrix is as follows\n',confusion_matrix(y_test,y_pred))
print('Accuracy Metrics\n',classification_report(y_test,y_pred))
print("Correct predicition ",accuracy_score(y_test,y_pred))
print("Worng predicition   ",(1-accuracy_score(y_test,y_pred)))

Confusion matrix is as follows
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Accuracy Metrics
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38

Correct predicition  0.9736842105263158
Worng predicition    0.02631578947368418


In [4]:
x_new=np.array([[5,2.9,1,0.2]])
print("\n XNEW \n",x_new)
prediction = kn.predict(x_new)
print("\n Predicted target value: {}\n".format(prediction))
print("\n Predicted feature name: {}\n".format(dataset["target_names"][prediction]))


 XNEW 
 [[5.  2.9 1.  0.2]]

 Predicted target value: [0]


 Predicted feature name: ['setosa']

